In [3]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
# на примере statsmodels
# X - массив со значениями НП, model - построенная регрессионная модель

model.predict(X)

NameError: name 'model' is not defined

In [3]:
import statsmodels.api as sm
import statsmodels.formula.api as smf 

# способ первый
# Y = одномерный массив с ЗП, X - массив со всеми нужными нам НП

X = sm.add_constant(X)  # добавить константу, чтобы был свободный член
model = sm.OLS(Y, X)  # говорим модели, что у нас ЗП, а что НП
results = model.fit()  # строим регрессионную прямую
print(results.summary())  # смотрим результат

# способ второй, потенциально более удобный

results = smf.ols('Y ~ X1 + X2 + ... + Xn', data).fit()
print(results.summary())

NameError: name 'X' is not defined

In [1]:
import seaborn as sns

sns.pairplot(data, kind = 'reg')

NameError: name 'data' is not defined

In [ ]:
g = sns.lmplot(x = 'sepal_length', y = 'sepal_width', data = iris, hue = 'species')
g._legend.set_title('Виды ирисов')
plt.title('Взаимосвязь измерений чашелистников ирисов')
plt.xlabel('Длина чашелистника')
plt.ylabel('Ширина чашелистника')

In [ ]:
import statsmodels.api as sm
import statsmodels.formula.api as smf 

# способ первый
# Y = одномерный массив с ЗП, X - массив со всеми нужными нам НП

X = sm.add_constant(X)  # добавить константу, чтобы был свободный член
model = sm.Logit(Y, X)  # говорим модели, что у нас ЗП, а что НП
results = model.fit()  # строим регрессионную прямую
print(results.summary())  # смотрим результат

# способ второй, потенциально более удобный
results = smf.logit('Y ~ X1 + X2 + ... + Xn', data).fit()
print(results.summary())

In [ ]:
import statsmodels.api as sm
import statsmodels.formula.api as smf 

# способ первый
# Y = одномерный массив с ЗП, X - массив со всеми нужными нам НП

X = sm.add_constant(X)  # добавить константу, чтобы был свободный член
model = sm.MNLogit(Y, X)  # говорим модели, что у нас ЗП, а что НП
results = model.fit()  # строим регрессионную прямую
print(results.summary())  # смотрим результат

# способ второй, потенциально более удобный
results = smf.mnlogit('Y ~ X1 + X2 + ... + Xn', data).fit()
print(results.summary())

In [ ]:
from sklearn.cluster import AgglomerativeClustering

clustering = AgglomerativeClustering().fit(X)

In [4]:
df = pd.read_csv('cars.csv')

In [5]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

# 2

In [6]:
df.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [7]:
df.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

# 3

In [8]:
df['Namecar'] = df['CarName'].apply(lambda x: x.split()[0])

In [9]:
df['Namecar'].nunique()

28

In [10]:
df['Namecar'] = df['Namecar'].apply(lambda x: x.lower())

In [11]:
df['Namecar'] = df['Namecar'].apply(lambda x: x.replace('vw','volkswagen').replace('vokswagen','volkswagen').replace('toyouta','toyota').replace('porcshce','porsche').replace('maxda','mazda'))

In [12]:
df['price'].corr(df['horsepower'])

0.8081388225362212

In [13]:
df.head(1)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,Namecar
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero

In [14]:
df_dummy = pd.get_dummies(data=df[['Namecar', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower', 'price']], drop_first = True)

In [15]:
df_dummy.columns

Index(['wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginesize',
       'boreratio', 'horsepower', 'price', 'Namecar_audi', 'Namecar_bmw',
       'Namecar_buick', 'Namecar_chevrolet', 'Namecar_dodge', 'Namecar_honda',
       'Namecar_isuzu', 'Namecar_jaguar', 'Namecar_mazda', 'Namecar_mercury',
       'Namecar_mitsubishi', 'Namecar_nissan', 'Namecar_peugeot',
       'Namecar_plymouth', 'Namecar_porsche', 'Namecar_renault',
       'Namecar_saab', 'Namecar_subaru', 'Namecar_toyota',
       'Namecar_volkswagen', 'Namecar_volvo', 'fueltype_gas',
       'aspiration_turbo', 'carbody_hardtop', 'carbody_hatchback',
       'carbody_sedan', 'carbody_wagon', 'drivewheel_fwd', 'drivewheel_rwd',
       'enginetype_dohcv', 'enginetype_l', 'enginetype_ohc', 'enginetype_ohcf',
       'enginetype_ohcv', 'enginetype_rotor', 'cylindernumber_five',
       'cylindernumber_four', 'cylindernumber_six', 'cylindernumber_three',
       'cylindernumber_twelve', 'cylindernumber_two'],
      dtype='object')

In [16]:
df_dummy

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price,Namecar_audi,Namecar_bmw,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
0,88.6,168.8,64.1,2548,130,3.47,111,13495.0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,88.6,168.8,64.1,2548,130,3.47,111,16500.0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,94.5,171.2,65.5,2823,152,2.68,154,16500.0,0,0,...,0,0,1,0,0,0,1,0,0,0
3,99.8,176.6,66.2,2337,109,3.19,102,13950.0,1,0,...,1,0,0,0,0,1,0,0,0,0
4,99.4,176.6,66.4,2824,136,3.19,115,17450.0,1,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,109.1,188.8,68.9,2952,141,3.78,114,16845.0,0,0,...,1,0,0,0,0,1,0,0,0,0
201,109.1,188.8,68.8,3049,141,3.78,160,19045.0,0,0,...,1,0,0,0,0,1,0,0,0,0
202,109.1,188.8,68.9,3012,173,3.58,134,21485.0,0,0,...,0,0,1,0,0,0,1,0,0,0
203,109.1,188.8,68.9,3217,145,3.01,106,22470.0,0,0,...,1,0,0,0,0,0,1,0,0,0
204,109.1,188.8,68.9,3062,141,3.78,114,22625.0,0,0,...,1,0,0,0,0,1,0,0,0,0

In [17]:
X = df_dummy['horsepower']
Y = df_dummy['price']
model = sm.OLS(Y, X)  # говорим модели, что у нас ЗП, а что НП
results = model.fit()  # строим регрессионную прямую
print(results.summary())  # смотрим результат

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.901
Model:                            OLS   Adj. R-squared (uncentered):              0.900
Method:                 Least Squares   F-statistic:                              1854.
Date:                Tue, 10 Oct 2023   Prob (F-statistic):                   2.43e-104
Time:                        22:06:16   Log-Likelihood:                         -2031.7
No. Observations:                 205   AIC:                                      4065.
Df Residuals:                     204   BIC:                                      4069.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
horsepower   132.0043      3.066     43.055      0.000     125.959     138.049
==============================================================================
Omnibus:                       83.232   Durbin-Watson:                   0.594
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              226.121
Skew:                           1.804   Prob(JB):                     7.92e-50
Kurtosis:                       6.667   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [18]:
0.901**2

0.811801

# 8

In [19]:
X = df_dummy[['wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginesize',
       'boreratio', 'horsepower', 'Namecar_audi', 'Namecar_bmw',
       'Namecar_buick', 'Namecar_chevrolet', 'Namecar_dodge', 'Namecar_honda',
       'Namecar_isuzu', 'Namecar_jaguar', 'Namecar_mazda', 'Namecar_mercury',
       'Namecar_mitsubishi', 'Namecar_nissan', 'Namecar_peugeot',
       'Namecar_plymouth', 'Namecar_porsche', 'Namecar_renault',
       'Namecar_saab', 'Namecar_subaru', 'Namecar_toyota',
       'Namecar_volkswagen', 'Namecar_volvo', 'fueltype_gas',
       'aspiration_turbo', 'carbody_hardtop', 'carbody_hatchback',
       'carbody_sedan', 'carbody_wagon', 'drivewheel_fwd', 'drivewheel_rwd',
       'enginetype_dohcv', 'enginetype_l', 'enginetype_ohc', 'enginetype_ohcf',
       'enginetype_ohcv', 'enginetype_rotor', 'cylindernumber_five',
       'cylindernumber_four', 'cylindernumber_six', 'cylindernumber_three',
       'cylindernumber_twelve', 'cylindernumber_two']]
Y = df_dummy['price']
sm.add_constant(X)
model = sm.OLS(Y, X)  # говорим модели, что у нас ЗП, а что НП
results = model.fit()  # строим регрессионную прямую
print(results.summary())  # смотрим результат

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.989
Model:                            OLS   Adj. R-squared (uncentered):              0.985
Method:                 Least Squares   F-statistic:                              300.8
Date:                Tue, 10 Oct 2023   Prob (F-statistic):                   2.09e-133
Time:                        22:06:16   Log-Likelihood:                         -1809.7
No. Observations:                 205   AIC:                                      3711.
Df Residuals:                     159   BIC:                                      3864.
Df Model:                          46
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
wheelbase               136.4413     77.983      1.750      0.082     -17.574     290.457
carlength              -110.4333     50.120     -2.203      0.029    -209.419     -11.447
carwidth                272.7002    117.376      2.323      0.021      40.884     504.517
curbweight                5.3896      1.565      3.443      0.001       2.298       8.481
enginesize               63.9099     24.197      2.641      0.009      16.120     111.700
boreratio             -4936.4670   1789.529     -2.759      0.006   -8470.780   -1402.154
horsepower               41.7665     18.270      2.286      0.024       5.683      77.850
Namecar_audi           1004.1792   2168.330      0.463      0.644   -3278.264    5286.623
Namecar_bmw            7983.1395   2155.851      3.703      0.000    3725.343    1.22e+04
Namecar_buick          3660.9604   2530.569      1.447      0.150   -1336.904    8658.825
Namecar_chevrolet     -2192.5070   2103.557     -1.042      0.299   -6347.024    1962.010
Namecar_dodge         -3176.5907   1726.269     -1.840      0.068   -6585.965     232.783
Namecar_honda         -2339.0666   1661.221     -1.408      0.161   -5619.973     941.839
Namecar_isuzu         -1303.9955   1858.734     -0.702      0.484   -4974.988    2366.997
Namecar_jaguar         2846.5143   2607.093      1.092      0.277   -2302.484    7995.513
Namecar_mazda          -754.7700   1682.149     -0.449      0.654   -4077.008    2567.468
Namecar_mercury       -1726.6988   2831.257     -0.610      0.543   -7318.420    3865.022
Namecar_mitsubishi    -3622.8853   1689.594     -2.144      0.034   -6959.827    -285.943
Namecar_nissan        -1429.5470   1601.109     -0.893      0.373   -4591.731    1732.637
Namecar_peugeot        -811.8027   1722.234     -0.471      0.638   -4213.208    2589.602
Namecar_plymouth      -3191.7589   1710.404     -1.866      0.064   -6569.799     186.282
Namecar_porsche        6373.5580   2820.405      2.260      0.025     803.269    1.19e+04
Namecar_renault       -2059.8576   2104.615     -0.979      0.329   -6216.463    2096.748
Namecar_saab            974.4934   1808.062      0.539      0.591   -2596.423    4545.410
Namecar_subaru        -8467.5054   3321.774     -2.549      0.012    -1.5e+04   -1907.015
Namecar_toyota        -2467.8809   1575.655     -1.566      0.119   -5579.793     644.031
Namecar_volkswagen    -2016.9997   1643.418     -1.227      0.222   -5262.743    1228.744
Namecar_volvo          1162.5472   1953.613      0.595      0.553   -2695.830    5020.925
fueltype_gas           -578.2480    922.963     -0.627      0.532   -2401.096    1244.600
aspiration_turbo        462.5828    691.293      0.669      0.504    -902.719    1827.885
carbody_hardtop       -2247.9581   1238.576     -1.815      0.071   -4694.141     198.224
carbody_hatchback     -2771.2066   1129.787     -2.453      0.015   -5002.532    -539.882
carbody_sedan         -1980.1532   1178.913     -1.680      0.095   -4308.502     348.196
carbody_wagon         -2719.1752   1252.184     -2.172      0.031   -5192.233    -246.117
drivewheel_fwd          477.7024    881.993      0.542      0.589   -1264.230    2219.635
drivewheel_rwd          650.8195   1054.816      0.617      0.538   -1432.439    2734.078
enginetype_dohcv      -9707.5281   4405.788     -2.203      0.029   -1.84e+04   -1006.114
enginetype_l          -1538.7705   1632.593     -0.943      0.347   -4763.135    1685.594
enginetype_ohc          -69.0261   1086.877     -0.064      0.949   -2215.603    2077.551
enginetype_ohcf        8009.7455   2618.820      3.059      0.003    2837.587    1.32e+04
enginetype_ohcv       -2608.6295   1241.674     -2.101      0.037   -5060.931    -156.328
enginetype_rotor       -773.3844   2124.559     -0.364      0.716   -4969.381    3422.612
cylindernumber_five   -6070.9626   2942.606     -2.063      0.041   -1.19e+04    -259.327
cylindernumber_four   -5600.4794   3569.945     -1.569      0.119   -1.27e+04    1450.149
cylindernumber_six    -7228.6546   2619.952     -2.759      0.006   -1.24e+04   -2054.260
cylindernumber_three   -726.9678   2724.595     -0.267      0.790   -6108.032    4654.096
cylindernumber_twelve -9921.1765   3649.261     -2.719      0.007   -1.71e+04   -2713.899
cylindernumber_two     -773.3844   2124.559     -0.364      0.716   -4969.381    3422.612
==============================================================================
Omnibus:                       72.615   Durbin-Watson:                   1.428
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              369.512
Skew:                           1.266   Prob(JB):                     5.77e-81
Kurtosis:                       9.071   Cond. No.                     1.01e+16
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The smallest eigenvalue is 1.37e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [20]:
X = df_dummy[['wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginesize',
       'boreratio', 'horsepower', 'fueltype_gas',
       'aspiration_turbo', 'carbody_hardtop', 'carbody_hatchback',
       'carbody_sedan', 'carbody_wagon', 'drivewheel_fwd', 'drivewheel_rwd',
       'enginetype_dohcv', 'enginetype_l', 'enginetype_ohc', 'enginetype_ohcf',
       'enginetype_ohcv', 'enginetype_rotor', 'cylindernumber_five',
       'cylindernumber_four', 'cylindernumber_six', 'cylindernumber_three',
       'cylindernumber_twelve', 'cylindernumber_two']]
Y = df_dummy['price']
sm.add_constant(X)
model = sm.OLS(Y, X)  # говорим модели, что у нас ЗП, а что НП
results = model.fit()  # строим регрессионную прямую
print(results.summary())  # смотрим результат

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.977
Model:                            OLS   Adj. R-squared (uncentered):              0.974
Method:                 Least Squares   F-statistic:                              290.8
Date:                Tue, 10 Oct 2023   Prob (F-statistic):                   3.70e-132
Time:                        22:06:17   Log-Likelihood:                         -1882.5
No. Observations:                 205   AIC:                                      3817.
Df Residuals:                     179   BIC:                                      3903.
Df Model:                          26
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
wheelbase                69.4047     87.190      0.796      0.427    -102.648     241.457
carlength               -46.9815     50.331     -0.933      0.352    -146.299      52.336
carwidth                255.8722    128.478      1.992      0.048       2.346     509.398
curbweight                3.7736      1.687      2.237      0.027       0.444       7.103
enginesize               32.5254     22.258      1.461      0.146     -11.396      76.446
boreratio             -2160.2931   1734.298     -1.246      0.215   -5582.593    1262.007
horsepower               89.3206     16.641      5.368      0.000      56.484     122.158
fueltype_gas          -2592.6432    968.868     -2.676      0.008   -4504.516    -680.770
aspiration_turbo      -1199.0873    787.466     -1.523      0.130   -2752.998     354.823
carbody_hardtop       -3607.2530   1519.579     -2.374      0.019   -6605.846    -608.660
carbody_hatchback     -4357.7234   1279.163     -3.407      0.001   -6881.902   -1833.544
carbody_sedan         -3078.5570   1344.209     -2.290      0.023   -5731.092    -426.022
carbody_wagon         -4178.0790   1464.235     -2.853      0.005   -7067.462   -1288.696
drivewheel_fwd          559.9328   1105.868      0.506      0.613   -1622.282    2742.148
drivewheel_rwd         2123.8282   1220.822      1.740      0.084    -285.227    4532.883
enginetype_dohcv      -1.736e+04   4545.624     -3.820      0.000   -2.63e+04   -8394.915
enginetype_l           2489.7235   1313.712      1.895      0.060    -102.632    5082.079
enginetype_ohc         4092.5442    896.812      4.563      0.000    2322.860    5862.229
enginetype_ohcf        5500.7582   1389.511      3.959      0.000    2758.829    8242.687
enginetype_ohcv       -5029.6776   1347.938     -3.731      0.000   -7689.571   -2369.784
enginetype_rotor      -5841.3923   2029.540     -2.878      0.004   -9846.294   -1836.491
cylindernumber_five   -1.456e+04   2851.310     -5.106      0.000   -2.02e+04   -8932.221
cylindernumber_four   -1.749e+04   3090.877     -5.660      0.000   -2.36e+04   -1.14e+04
cylindernumber_six    -1.299e+04   2083.890     -6.235      0.000   -1.71e+04   -8880.467
cylindernumber_three  -1.148e+04   4446.797     -2.582      0.011   -2.03e+04   -2708.949
cylindernumber_twelve -1.282e+04   3352.741     -3.825      0.000   -1.94e+04   -6208.209
cylindernumber_two    -5841.3923   2029.540     -2.878      0.004   -9846.294   -1836.491
==============================================================================
Omnibus:                       18.911   Durbin-Watson:                   1.299
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               49.647
Skew:                           0.328   Prob(JB):                     1.66e-11
Kurtosis:                       5.320   Cond. No.                     1.01e+16
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The smallest eigenvalue is 1.37e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

# 9

In [21]:
-1.793 * np.e**(-14)

-1.4909309933526982e-06

In [22]:
-1.4909309933526982 * np.e**(-6)

-0.003695648445032338